image:
  repository: jesus950810/diplomado
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

serviceAccount:
  create: true
  name: diplomado-sa

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: diplomado.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

replicaCount: 1